### PR TITLE
Prep for release to Maven Central

### PR DESCRIPTION
**Pull request by caniszczyk**

### CODE REVIEW

**Comment by caniszczyk** [comment]
There we go, much better.

@jakl, does this look OK to you?

**Comment by jakl** [comment]
This looks great - I'll try it in the morning.

**Comment by caniszczyk** [comment]
Thanks, the code is now in Maven Central (I published it earlier)

http://search.maven.org/#artifactdetails%7Ccom.twitter%7Ctwitter-text%7C1.6.1%7Cjar

**Comment by jakl** [comment]
Thanks so much. I'll run `mvn deploy -Psonatype-oss-release` when releasing new versions now.

**Pull request merged**
